name: dotnet
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.304'
      - run: dotnet restore
      - run: dotnet build -c Release --no-restore
      - run: dotnet test --no-build --collect:"XPlat Code Coverage"

